condition is added to test pypi publish
ghga-de/gh-action-pypi pull request #6
Opened 2024-03-11 12:02 UTC by sbilge

2024-03-11 14:11 UTC, lkuchenb requested changes
To be transparent about what this flag does I would rename it to `test_pypi`. Also the description of the flag should be changed to something like "Publish to TestPyPI instead of PyPI"

2024-03-18 10:15 UTC, ckaipf approved these changes, later dismissed

2024-04-23 11:26 UTC, ckaipf submitted a review, later dismissed

2024-04-23 20:10 UTC, lkuchenb requested changes
The description is still off, right? It's not skipping anything, it's either publishing in pypi or in test-pypi.

2024-05-08 11:45 UTC, lkuchenb approved these changes

2024-05-10 09:38 UTC, merged